//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKSNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string ID { get; set; }
        public string Ten { get; set; }
        public byte[] Hinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public int IDchucvu { get; set; }
        public int IDbophan { get; set; }
    
        public virtual BangLuong BangLuong { get; set; }
        public virtual BoPhan BoPhan { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual User User { get; set; }
    }
}
