//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKSNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public int ID { get; set; }
        public int IDdichvu { get; set; }
        public int IDphong { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
